---
- name: Install iptables
  ansible.builtin.package:
    name:
      - iptables
      - iptables-persistent
    state: present

- name: Template firewall
  ansible.builtin.template:
    src: "templates/{{ group_names[0] }}.rules.v4"
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: "0600"
    backup: true
  notify: Restore firewall
