---
- name: Stow config
  ansible.builtin.shell: stow -v -S --adopt --no-folding *
  args:
    chdir: "{{ user_conf }}"
  changed_when: true

- name: Reset files adopted by stow
  ansible.builtin.command: git reset --hard
  args:
    chdir: "{{ user_conf }}"
  changed_when: true
  tags:
    - skip_ansible_lint
