---
- name: Postmap sasl_passwd
  ansible.builtin.command: postmap /etc/postfix/sasl_passwd
  changed_when: true

- name: Postmap sender_canonical
  ansible.builtin.command: postmap /etc/postfix/sender_canonical
  changed_when: true

- name: Reload postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded
