---
- name: Postmap sasl/passwd
  ansible.builtin.command: postmap /etc/postfix/sasl/passwd
  changed_when: true

- name: Postmap sender_canonical
  ansible.builtin.command: postmap /etc/postfix/sender_canonical
  changed_when: true

- name: Reload postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded

- name: Restart saslauthd
  ansible.builtin.service:
    name: saslauthd
    state: restarted

